config/routes.rb
Rails.application.routes.draw do
  get 'conversations/index'

  post "toggle_like" => "likes#toggle"

  post 'search' => "home#index"
  post 'confirm' => "friendships#confirm"
  get 'received_requests' => "friendships#received_requests"
  get 'sent_requests' => "friendships#sent_requests"
  get "friends" => "friends#index"
  delete "remove_friend" => "friendships#destroy"

  get 'test' => 'conversations#index'

  resources :friendships
  resources :posts
  resources :comments
  resources :conversations

  resources :users do
    member do
      get 'profile'
    end
    collection do
      get :search
    end
  end

  resources :messages do
    collection do
      get :inbox
      get :sent
    end
  end

  get "profile" => "users#edit"

  get 'auth/:provider/callback' => 'sessions#callback'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  get 'search' => 'home#index'

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  belongs_to :user
  belongs_to :post
  has_many :photos, as: :attachment, dependent: :destroy

  validates :body, presence: true

  has_ancestry

  has_many :likes, as: :item, dependent: :destroy

  def liked?(user)
    likes.include?(user_id: user)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.create!(comment_params)
    @parent = params[:comment][:parent_id]

    if params[:comment][:photo]
      @photo = Photo.create!(user_id: current_user.id, attachment_type: "Comment", attachment_id: @comment.id)
      uploader = PhotoUploader.new
      uploader.store! params[:comment][:photo]
      @photo.url = uploader.url
      @photo.save
    end

    respond_to do |format|
      if @comment.save
        format.html {redirect_back(fallback_location: root_path)}
        format.js
      else
        flash[:warning] = 'Could not create comment. Please try again.'
        format.html {redirect_back(fallback_location: root_path)}
        format.js
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @parent = @comment.parent
    respond_to do |format|
      format.js
      @comment.destroy
      @parent.save
      @parent = @parent.id
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:user_id, :body, :post_id, :parent_id, :photo)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def nested_comments(comment)
    comment.children.map do |comment, sub_comments|
      render(comment)
    end.join.html_safe
  end
end

app/views/comments/_comment.html.erb
<div class="comment" id="comment_<%= comment.id %>">
  <div class="columns" style="width: 100%">
    <% if current_user %>
      <%= image_tag(comment.user.image_url_or_default, size: "32x32", style: "margin-right: 10px") %>

      <div class="comment-body" style="width:100%">
        <%= link_to "#{comment.user.name} ", profile_user_path(comment.user), style: "font-weight: bold; white-space: pre;" %>
        <%= comment.body %>
          <% if comment.photo.url %>
            <%= link_to(comment.photo.url, "data-lightbox" => "test")  do  %>
            <%= image_tag comment.photo.url, style: 'height:auto;width:auto;' %>
            <% end %>
          <% end %> <br>

        <div class="replies hidden">
          <% comment.children.each do |reply| %>
            <%= render 'comments/replies', {comment: reply} %>
          <% end %>
        </div>

        <div class="comment-likes">
          <% unless comment.parent %>
            <%= link_to comment.children.count >= 1 ? comment.children.count.to_s + " Replies" : "Reply", "#", style: "font-size: .7em", id: "js-reply-comment-" + comment.id.to_s %>
          <% end %>
          
          <%= form_tag toggle_like_path, method: :post, remote: true do %>
            <%= hidden_field_tag :comment_id, comment.id %>
              <div class="field">
                <div class="control">
                  <button class="js-like-button-<%= comment.id %> button is-white <%= 'is-liked' if current_user.liking?(comment) %>"
                    style="font-size: .7em">
                    <%= render partial: "comments/like_button", locals: {comment: comment, user: current_user} %>
                  </button>
                </div>
              </div>
          <% end %>
          <p style="font-size: .7em">
            <%= time_ago_in_words(comment.created_at) %> ago
          </p>
        </div>
        <%= render 'comments/reply_comment', comment: comment %>
      </div>

      <% if current_user.comments.include?(comment) %>
        <%= form_tag comment_path(comment), class: "form-delete-comment", method: :delete, remote: true do %>
        <%= image_submit_tag("X.png", class: "comment-destroy") %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/comments/_comment_form.html.erb
<div class="card js-post-comment-form">
  <div class="card-content">
    <div class="media">
      <div class="media-left">
        <figure class="image is-32x32">
          <%= image_tag(current_user.image_url_or_default) %>
        </figure>
      </div>
      <div class="content" style="width: 100%">
        <div class="field has-addons" style="align-items: center; padding-bottom: 10px">
          <div class="control has-icons-left is-expanded">
            <%= form_for post.comments.build do |f| %>
            <%= f.hidden_field :user_id, value: current_user.id %>
            <%= f.hidden_field :post_id, value: post.id %>
            <%= f.text_field :body, class: "input comment-body", placeholder: "Comment...", autocomplete: "off", required: true %>
              <span class="icon is-small is-left">
                <i class="fa fa-comments"></i>
              </span>
            <div class="control">
              <label class="file-label">
              <%= f.file_field :photo, class: "file-input" %>
                <span class="file-cta">
                  <span class="file-icon">
                    <i class="fa fa-camera-retro"></i>
                  </span>
                  <span class="file-label">Photo…</span>
                </span>
              </label>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/comments/_like_button.html.erb
<% liked = user.liking?(comment) %>
<% icon_type = get_like_button_icon(liked) %>
<% button_classes = get_like_button_classes_small(liked)%>
<% button_text = get_like_button_text(liked) %>
<% comment.likes.count > 2 ? button_text += "s #{comment.likes.count}" : button_text %>

<%= link_to fa_icon(icon_type, text: button_text), toggle_like_path(comment_id: comment),
    class: button_classes, method: "post", remote: true %>

app/views/comments/_replies.html.erb
<%= render comment %>

app/views/comments/_reply_comment.html.erb
<div class="js-reply-comment hidden">
  <div class="media">
    <div class="media-left">
      <figure class="image is-32x32">
        <%= image_tag(current_user.image_url_or_default) %>
      </figure>
    </div>
    <div class="content" style="width:100%">
      <div class="field has-addons" style="align-items: center; padding-bottom: 10px; width:100%">
        <%= form_for Comment.create, autocomplete: "off", remote: true do |f|%>
          <%= f.hidden_field :parent_id, value: comment.id %>
          <%= f.hidden_field :post_id, value: comment.post.id %>
          <%= f.text_field :body, class: "input reply-form", autocomplete: "off", required: true, style: "width: 100%" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/comments/create.js.erb
<% if @comment.parent %>
  $("#comment_<%= @parent %> form").trigger("reset");
  $("#comment_<%= @parent %>").find(".replies").append("<%= j render @comment %>");
  $("#comments_<%= @parent %>").html("<%= @comment.parent.children.count %> Replies");
<% else %>
  $(".js-comments-<%= @comment.post.id %>").last(".comment").append("<%= j render @comment %>");
  $("input.input").val('');
  $(".comment-button-<%= @comment.post.id %>").html("<i class='fa fa-comment'></i><%= @comment.post.comments_count %>");
  $(".js-comments-<%= @comment.post.id %>").parent(".card.is-multiline").removeClass("hidden-comment").addClass("active");
<% end %>

app/views/comments/destroy.js.erb
<% if @comment.parent %>
  $("#comments_<%= @parent %>").html("<%= @comment.parent.children.count %> Replies")
  console.log("@comment.id")
  $("#comment_<%= @comment.id %>").remove();
<% else %>
  $("#comment_<%= @comment.id %>").remove();
  $(".comment-button-<%= @comment.post.id %>").html("<i class='fa fa-comment'></i><%= @comment.post.comments_count %>")
<% end %>