config/routes.rb
Rails.application.routes.draw do
  get 'conversations/index'

  post "toggle_like" => "likes#toggle"

  post 'search' => "home#index"
  post 'confirm' => "friendships#confirm"
  get 'received_requests' => "friendships#received_requests"
  get 'sent_requests' => "friendships#sent_requests"
  get "friends" => "friends#index"
  delete "remove_friend" => "friendships#destroy"

  get 'test' => 'conversations#index'

  resources :friendships
  resources :posts
  resources :comments
  resources :conversations

  resources :users do
    member do
      get 'profile'
    end
    collection do
      get :search
    end
  end

  resources :messages do
    collection do
      get :inbox
      get :sent
    end
  end

  get "profile" => "users#edit"

  get 'auth/:provider/callback' => 'sessions#callback'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  get 'search' => 'home#index'

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  mount_uploader :photo, PhotoUploader

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :photos, dependent: :destroy

  has_many :sent_messages, class_name: "Message", foreign_key: "sender_id"
  has_many :received_messages, class_name: "Message", foreign_key: "recipient_id"

  has_many :messages
  has_many :user_conversations
  has_many :conversations, through: :user_conversations


  has_many :mentions, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true, uniqueness: {case_sensitive: false}

  has_secure_password

  def titleize_name
    name.titleize if name
  end

  def self.autocomplete_by_name(letters)
    where("name ILIKE ?", "%#{letters}%")
  end

  def self.search(search)
    User.where("name ILIKE ? ", "%#{search}%")
  end

  def self.from_omniauth(auth)
    # Check out the Auth Hash function at https://github.com/mkdynamic/omniauth-facebook#auth-hash
    # and figure out how to get email for this user.
    # Note that Facebook sometimes does not return email,
    # in that case you can use facebook-id@facebook.com as a workaround
    email = auth[:info][:email] || "#{auth[:uid]}@facebook.com"
    user = where(email: email).first_or_initialize
    user.image_url = auth[:info][:image]
    user.name = auth[:info][:name]
    user.password = SecureRandom.hex
    user.save && user
  end

  def image_url_or_default
    avatar.url || image_url.presence || "http://lorempixel.com/128/128/sports/Fake-User/"
  end

  def is_friend?(user)
    friends.include?(user)
  end

  def self.generate_users(n = 5, gender = "female")
    url = "https://randomuser.me/api?results=#{n}&gender=#{gender}&nat=US"
    body = HTTP.get(url).parse
    body["results"].each do |person|
      hash = {}
      hash[:name] = person["name"]["first"] + " " + person["name"]["last"]
      hash[:email] = person["email"]
      hash[:password] = person["login"]["password"]
      hash[:image_url] = person["picture"]["large"]
      hash[:image_url] = person["location"]["state"]
      hash[:image_url] = person["location"]["city"]
      User.create! hash
    end
  end

  def friends
    fs = friendships.select {|fs| fs.status == "accepted"}
    fs.map {|fs| User.find(fs.friend_id) }
  end

  def received_requests
    friendships.where(status: nil).map {|fs| User.find(fs.friend_id)}
  end

  def friend_names
    friends.map{|e| e.name}
  end

  def sent_requests
    friends = friendships.map {|e| (e.user_id == id && e.status == "pending") ? e : next}
    friends.delete(nil)
    friends.map { |friend| User.find(friend[:friend_id]) }
  end

  def self.recipient_options(user)
    user.friends.map{|e| [e.titleize_name, e.id]}
  end

  def like_id(id, post)
    like = post.likes.where(user_id: id)[0]
  end

  def toggle_like!(item)
    if like = likes.where(item: item).first
      like.destroy
    else
      likes.where(item: item).create!
    end
  end

  def liking?(item)
    likes.where(item: item).exists?
  end

  def timeline_posts
    Post.where("user_id = ? or wall_id = ? ", id, id).order('created_at DESC').uniq
  end

  def sorted_conversations
    conversations.joins(:messages).order('messages.created_at DESC').uniq
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:index]

  def new
    @user = User.new
  end

  def search
    @users = User.autocomplete_by_name(params[:q])

    respond_to do |format|
      format.json
    end
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = "Welcome to Railsbook #{@user.name}"
      login(@user)
      UserMailer.welcome_email(@user).deliver_now
      redirect_to root_path
    else
      flash[:success] = "Could not create."
      render 'new'
    end
  end

  def profile
    @user = User.find(params[:id])
    @posts = @user.timeline_posts
  end

  def edit
    @user = current_user
  end

  def update
    current_user.update(user_params)
    redirect_to root_path
  end

  def index
    @users = User.all
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_sidebar.html.erb
<div class="column is-3" style="margin-top: -100px">
  <aside class="menu">
    <div class="field">
      <div class="control">
        <%= image_tag @user.image_url_or_default, size: "250x250", style: "border: 3px solid white; border-radius: 3px" %>
      </div>
    </div>
    <nav class="panel">
      <a class="panel-block">
          <span class="panel-icon">
            <i class="fa fa-info"></i>
          </span>
          <%= @user.quote if @user.quote %>
        </a>
        <a class="panel-block">
          <span class="panel-icon">
            <i class="fa fa-briefcase"></i>
          </span>
          <%= @user.position if @user.position %>
        </a>
        <a class="panel-block">
          <span class="panel-icon">
            <i class="fa fa-book"></i>
          </span>
          <%= @user.school if @user.position %>
        </a>
        <a class="panel-block">
          <span class="panel-icon">
            <i class="fa fa-map-o"></i>
          </span>
          <%= @user.city + ", " + @user.state if @user.city && @user.state %>
        </a>
    </nav>
  </aside>
  <%= form_for(@user) do |f| %>
  <%= f.file_field :avatar %>
  <%= f.hidden_field :avatar_cache %>
  <%= f.submit "Upload" %>
  <% end %>
<% @user.photos.each do |photo| %>
  <%= image_tag(photo.url, size: "500x500") %>
<% end %>

</div>

app/views/users/edit.html.erb
<div class="columns">
  <div class="column is-3">
    <aside class="menu">
      <p class="menu-label">Profile</p>
      <div class="field">
        <div class="control">
          <%= image_tag current_user.image_url_or_default %>
        </div>
      </div>
      <ul class="menu-list">
        <li><%= link_to "Friends (#{current_user.friends.count})", friends_path, class: "navbar-item #{'is-active' if current_page? profile_path }" %></li>
        <li><%= link_to "Friend Requests(#{current_user.received_requests.count})", received_requests_path, class: "navbar-item #{'is-active' if current_page? profile_path }"  %></li>
      </ul>
    </aside>
  </div>
  <div class="column">
    <div class="card user-card">
      <div class="card-content">
        <%= form_for @user do |f| %>
          <div class="field">
            <div class="control">
              <%= f.text_field :name, class: 'input' %>
            </div>
          </div>
          <div class="field">
            <div class="label">Email</div>
            <div class="control">
              <%= f.text_field :email, class: 'input' %>
            </div>
          </div>
          <div class="field">
            <div class="label">Passworrd</div>
            <div class="control">
              <%= f.password_field :password, class: 'input' %>
            </div>
          </div>

          <div class="field">
            <div class="label">URL</div>
            <div class="control">
              <%= f.text_field :image_url, class: 'input' %>
            </div>
          </div>
          <div class="field">
            <%= f.label :avatar, class: "label" %>
            <div class="control"><%= f.file_field :avatar, class: "input" %></div>
          </div>          
          <%= f.submit "Save", class: "button is-primary" %>
        <% end %>
      </div>
    </div>

app/views/users/index.html.erb
<div class="columns is-multiline">
  <% User.all.each do |other_user| %>
  <% next if current_user.id == other_user.id %>
    <!-- column -->
    <div class="column is-6">
      <!-- card -->
      <div class="card">

        <!-- card-header -->
        <header class="card-header">
          <%= link_to image_tag(other_user.image_url_or_default), profile_user_path(other_user), class: "hvr-grow" %>
          <p class="card-header-title"><%= other_user.titleize_name %></p>
        </header>
        <!-- close header -->

        <!-- card-content -->
        <div class="card-content">
          <div class="content js-user-<%= other_user.id %>">
            <% if current_user.sent_requests.include?(other_user) %>
              <%= link_to icon("user-times", "Cancel Request"), remove_friend_path(user_id: other_user.id), class: "button is-danger add-remove", method: :delete, remote: true %>
            <% else %>
            <%= form_for current_user.friendships.build(friend: other_user, status: "pending", user_id: other_user.id), remote: true do |f| %>
              <%= f.hidden_field :user_id %>
              <%= f.hidden_field :friend_id %>

              <%= f.hidden_field :status %>
              <button class="button is-primary add-remove"><%= icon("user-plus", "Add Friend") %></button>
            <% end %>
          <% end %>
          </div>
        </div>
        <!-- close content -->
      </div>
      <!-- close card -->
    </div>
    <!-- close column -->
  <% end %>
</div>

app/views/users/new.html.erb
<div class="columns">
  <div class="column is-one-third is-centered">
    <div class="card">
      <div class="card-header">
        <h1 class="card-header-title">Create An Account</h1>
      </div>
      <div class="card-content">
        <%= form_for @user do |f| %>
          <div class="field">
            <%= f.text_field :name, placeholder: "Name...", class: "input" %>
          </div>
          <div class="field">
            <%= f.text_field :email, placeholder: "Email...", class: "input" %>
          </div>
          <div class="field">
            <%= f.password_field :password, placeholder: "Password...", class: "input" %>

          </div>
          <div class="field">
            <%= f.submit "Register", class: "button is-primary" %>
          </div>
        <% end %>
        <div class="field">
          <%= button_to "Facebook", "/auth/facebook", class: "button facebook", style: "margin-top: 15px" %>
        </div>
      </div>
      <div class="card-footer">
      </div>
    </div>
  </div>

app/views/users/profile.html.erb
<div class="wall">
  <div class="coverphoto">
  </div>
<%= form_for(@user) do |f| %>
  <%= f.hidden_field :user_id, value: @user.id %>
<% end %>
  <div class="columns">
    <%= render 'sidebar' %>
    <div class="column is-9 profile-column" style="margin-top: -100px">
      <section class="section profile-name">
        <div class="container">
          <h1 class="title name"><%= @user.name %></h1>
        </div>
      </section>
      <div class="body js-profile-tabs">
        <div class="column is-10 is-offset-1">
          <div class="tabs is-large">
            <ul>
              <li class="is-active" data-panel="js-timeline"><a>Timeline</a></li>
              <li class="" data-panel="js-about"><a>About</a></li>
              <li class="" data-panel="js-friends"><a>Friends</a></li>
              <li class="" data-panel="js-photos"><a>Photos</a></li>
              <li class="" data-panel="js-more"><a>More</a></li>
            </ul>
          </div>
          <%= render 'posts/post_form' %>
          <div id="my-posts">
            <%= render @posts %>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>