config/routes.rb
Rails.application.routes.draw do
  get 'conversations/index'

  post "toggle_like" => "likes#toggle"

  post 'search' => "home#index"
  post 'confirm' => "friendships#confirm"
  get 'received_requests' => "friendships#received_requests"
  get 'sent_requests' => "friendships#sent_requests"
  get "friends" => "friends#index"
  delete "remove_friend" => "friendships#destroy"

  get 'test' => 'conversations#index'

  resources :friendships
  resources :posts
  resources :comments
  resources :conversations

  resources :users do
    member do
      get 'profile'
    end
    collection do
      get :search
    end
  end

  resources :messages do
    collection do
      get :inbox
      get :sent
    end
  end

  get "profile" => "users#edit"

  get 'auth/:provider/callback' => 'sessions#callback'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  get 'search' => 'home#index'

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"

  def confirm
    self.status = "accepted"    
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    current_user.friendships.create!(friendship_params)
    current_user.friendships.last.confirm
    Friendship.create!(user_id: params[:friendship][:friend_id], friend_id: params[:friendship][:user_id])

    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.js { render "create", :locals => {user_id: params[:friendship][:friend_id]} }
    end
  end

  def destroy
    current_user.friendships.where(friend: params[:user_id]).first.delete
    Friendship.where(user_id: params[:user_id], friend_id: current_user.id)[0].destroy

    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.js { render "destroy", :locals => {user_id: params[:user_id]} }
    end
  end

  def confirm
    friendship = current_user.friendships.where(friend: params[:friend])[0]
    friendship.confirm
    friendship.save!
    friendship = Friendship.where("user_id = ? AND friend_id = ?", params[:friend], current_user.id)[0]
    friendship.confirm
    friendship.save!
    redirect_back(fallback_location: root_path)
  end

  def received_requests
    @requests = current_user.received_requests
  end

  def sent_requests
    @sent_requests = current_user.sent_requests
  end

  private
  def friendship_params
    params.require(:friendship).permit(:user_id, :friend_id, :status)
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/confirm.html.erb
<h1>Friends Requests</h1>

app/views/friendships/create.html.erb
<h1>Friendships#create</h1>
<p>Find me in app/views/friendships/create.html.erb</p>

app/views/friendships/create.js.erb
console.log("<%= user_id %>");
$(".js-user-<%= user_id %>").html("<a class='button is-danger add-remove' rel='nofollow' data-method='delete' data-remote='true' href='/remove_friend?user_id=<%= user_id %>'><span class='icon'><i class='fa fa-user-times'></i></span><span>Cancel Request</span></a>")

app/views/friendships/destroy.html.erb
<h1>Friendships#destroy</h1>
<p>Find me in app/views/friendships/destroy.html.erb</p>

app/views/friendships/destroy.js.erb
console.log("<%= user_id %>")
$(".js-user-<%= user_id %>").html("<form class='new_friendship' id='new_friendship' action='/friendships' accept-charset='UTF-8' data-remote='true' method='post'><input name='utf8' type='hidden' value='✓'><input type='hidden' value='1' name='friendship[user_id]' id='friendship_user_id'><input type='hidden' value='<%= user_id %>' name='friendship[friend_id]' id='friendship_friend_id'><input type='hidden' value='pending' name='friendship[status]' id='friendship_status'><button class='button is-primary add-remove'><span class='icon'><i class='fa fa-user-plus'></i></span><span>Add Friend</span></button></form>")

app/views/friendships/edit.html.erb
<h1>Friendships#edit</h1>
<p>Find me in app/views/friendships/edit.html.erb</p>

app/views/friendships/index.html.erb
<h1>Friendships#index</h1>
<p>Find me in app/views/friendships/index.html.erb</p>

app/views/friendships/received_requests.html.erb
<h1>Friendship Requests</h1>
<div class="columns is-multiline">
<% @requests.each do |user| %>
    <!-- column -->
    <div class="column is-6">
      <!-- card -->
      <div class="card">

        <!-- card-header -->
        <header class="card-header">
          <%= link_to image_tag(user.image_url_or_default), profile_user_path(user), class: "hvr-grow" %>
          <p class="card-header-title"><%= user.titleize_name %></p>
        </header>
        <!-- close header -->

        <!-- card-content -->
        <div class="card-content">
          <div class="content">
          <%= link_to "Accept", confirm_path(friend: user.id), method: :post %>
          </div>
        </div>
        <!-- close content -->
      </div>
      <!-- close card -->
    </div>
    <!-- close column -->
  <% end %>
</div>

app/views/friendships/sent_requests.html.erb
<h1>Pending Requests</h1>
<div class="columns is-multiline">
<% @sent_requests.each do |user| %>
    <!-- column -->
    <div class="column is-6">
      <!-- card -->
      <div class="card">

        <!-- card-header -->
        <header class="card-header">
          <%= link_to image_tag(user.image_url_or_default), profile_user_path(user), class: "hvr-grow" %>
          <p class="card-header-title"><%= user.titleize_name %></p>
        </header>
        <!-- close header -->

        <!-- card-content -->
        <div class="card-content">
          <div class="content">
            <%= user.id %>
          <%= link_to "Cancel", remove_friend_path(user_id: user.id), method: :delete %>
          </div>
        </div>
        <!-- close content -->
      </div>
      <!-- close card -->
    </div>
    <!-- close column -->
  <% end %>
</div>