config/routes.rb
Rails.application.routes.draw do
  get 'conversations/index'

  post "toggle_like" => "likes#toggle"

  post 'search' => "home#index"
  post 'confirm' => "friendships#confirm"
  get 'received_requests' => "friendships#received_requests"
  get 'sent_requests' => "friendships#sent_requests"
  get "friends" => "friends#index"
  delete "remove_friend" => "friendships#destroy"

  get 'test' => 'conversations#index'

  resources :friendships
  resources :posts
  resources :comments
  resources :conversations

  resources :users do
    member do
      get 'profile'
    end
    collection do
      get :search
    end
  end

  resources :messages do
    collection do
      get :inbox
      get :sent
    end
  end

  get "profile" => "users#edit"

  get 'auth/:provider/callback' => 'sessions#callback'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  get 'search' => 'home#index'

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsbook</title>
    <link rel="icon" href="http://coolspotters.com/files/photos/26546/ruby-on-rails-profile.png">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= tag :meta, name: :psj, action: action_name, controller: controller_name %>
  </head>

  <body>
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
          <a class="navbar-item" href="/">
            <%= image_tag "human-hydrogen.png", alt: "Humanbook" %>
          </a>
          <div class="navbar-item">
            <div class="field">
              <div class="control has-icons-left">
                <%= form_tag(search_path, id: "search-form") do %>
                  <%= text_field_tag :search, params[:search], class: "input", placeholder: "Search Posts", required: true %>
                  <span class="icon is-small is-left">
                    <i class="fa fa-search"></i>
                  </span>
                <% end %>
              </div>
            </div>
          </div>

          <div class="navbar-burger burger" data-target="navMenu">
            <span></span>
            <span></span>
            <span></span>
          </div>
        </div>
        <div class="navbar-menu" id="navMenu">
          <div class="navbar-start">
          </div>
          <div class="navbar-end">
            <% if current_user %>
              <%= link_to profile_user_path(current_user), class: "navbar-item" do %>
                <%= image_tag current_user.image_url_or_default %>
                &nbsp;<%= current_user.titleize_name %>
              <% end %>

              <div class="navbar-item has-dropdown is-hoverable">
                  <%= link_to "Inbox", inbox_messages_path, class: "navbar-item" %>
              </div>

              <div class="navbar-item has-dropdown is-hoverable">
                <a href="/" class="navbar-link">
                  <%= icon("users", "Friends") %>
                </a>

                <div class="navbar-dropdown">
                  <%= link_to "Friends (#{current_user.friends.count})", friends_path, class: "navbar-item" %>
                  <%= link_to "Sent Requests(#{current_user.sent_requests.count})", sent_requests_path, class: "navbar-item" %>
                  <%= link_to "Users", users_path, class: "navbar-item" %>
                </div>
              </div>

              <%= link_to icon("sign-out", "Log out"), logout_path, class: "navbar-item" %>
            <% else %>
              <%= link_to "Sign Up", new_user_path, class: "navbar-item" %>
              <%= link_to "Log In", login_path, class: "navbar-item" %>
            <% end %>
          </div>
        </div>
      </nav>
    </div>
    <%= flash_messages %>
      <%= content_for?(:content) ? yield(:content) : yield %>
  </body>
</html>
<div>




</div>

app/views/layouts/conversations.html.erb
<%= content_for :content do %>
<div class="columns conversations-main" style="overflow: hidden;">

  <div class="column is-one-quarter conversations-aside">
    <div id="my-conversations">
      <%= render @conversations %>
    </div>

    <div id="infinite-scrolling">
      <%= paginate @conversations %>
    </div>

  </div>
  <div class="column" style="padding-left: 0px; border-left: 1px solid #d3d3d3;">
    <%= yield %>
  </div>
</div>
  <% end %>
<%= render file: "layouts/application" %>

app/views/layouts/home.html.erb
<%= content_for :content do %>
<div class="container">
  <div class="columns" style="margin-top: 15px">
    <div class="column is-2">
      <aside class="menu">
        <p class="menu-label"><%= link_to image_tag(current_user.image_url_or_default, size: "100x100"), profile_user_path(current_user) %></p>
        <ul class="menu-list">
          <li>Test</li>
        </ul>
      </aside>

    </div>
    <div class="column is-10">
      <%= yield %>
    </div>
  </div>
</div>  
<% end %>

<%= render file: "layouts/application" %>

app/views/layouts/messages.html.erb
<%= content_for :content do %>
  <div class="columns">
    <div class="column is-one-quarter">
      <aside class="menu">
        <p class="menu-label">Messages</p>
        <ul class="menu-list">
          <li><%= link_to "Compose", new_message_path, class: "#{'is-active' if current_page? new_message_path }"  %></li>
          <li><%= link_to "Inbox", inbox_messages_path, class: "#{'is-active' if current_page? inbox_messages_path }" %></li>
          <li><%= link_to "Sent", sent_messages_path, class: "#{'is-active' if current_page? sent_messages_path }"  %></li>
        </ul>
      </aside>
    
    </div>
    <div class="column">
      <%= yield %>
    </div>
  </div>
  
<% end %>



<%= render file: "layouts/application" %>